name: The workflow
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:

    build_run:

        name: Build and Run on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]        

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '6.0.*'

            - name: Build
              run: |
                dotnet build --configuration Release /WarnAsError

            - name: Run
              run: |
                dotnet run
